### PR TITLE
[rqt_image_view] Set image topic with argv for rqt_image_view

### PR DESCRIPTION
**Pull request by wkentaro**
## Feature

**Before**
screen shot 2016-07-16 at 22 47 06

**After**

screen shot 2016-07-16 at 22 45 45

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The lines directly above the added code are supposed to already do exactly that. The question is why does the context not know about the argv? So I think this needs a different fix to be addressed properly.

**Comment by dirk-thomas** [comment]
I have just tried to pass an image topic to the plugin and it was working for me with both of the following invocations:

* `rqt_image_view foo`
* `rosrun rqt_image_view rqt_image_view foo`

I tested it with the Debian packages of ROS Kinetic

**Comment by wkentaro** [comment]
I'm using ubuntu 14.04 + indigo + rqt_image_view==0.3.13.

**Comment by dirk-thomas** [comment]
Can you please try to run the global executable without `rosrun`: just `rqt_image_view /pointcloud_to_mask_image/output`

**Comment by wkentaro** [comment]
Actually it also won't work.
image
image

**Comment by dirk-thomas** [comment]
Superseded by #391.

**Pull request closed without merging**
