### PR TITLE
rqt_image_view: Adding the possibility to publish mouse events.

### PR DESCRIPTION
**Pull request by v-lopez**
@ablasdel Merging #331 into master as requested. Apologies about the delay.

### CODE REVIEW

**Comment by ablasdel** [comment]
@dirk-thomas this still looks the same to me so i'm :+1: are you still good with merge?

**Comment by dirk-thomas** [comment]
Please hold the merge until the Qt 5 branch has been merged.

**Comment by ablasdel** [comment]
with https://github.com/ros-visualization/rqt_common_plugins/pull/359 merged are we good to go @dirk-thomas ?

**Comment by dirk-thomas** [comment]
This can be merged but we should release Indigo / Jade packages at the moment. I would like to have more time for people to test the current master with Indigo / Jade and Qt 4 to ensure that the Kinetic work didn't introduce any regressions.

**Comment by dirk-thomas** [comment]
This can be merged but we shouldn't release Indigo / Jade packages at the moment. I would like to have more time for people to test the current master with Indigo / Jade and Qt 4 to ensure that the Kinetic work didn't introduce any regressions.

**Pull request merged**
