### PR TITLE
Issue#296 Adding the required change in xterm_widget.py

### PR DESCRIPTION
**Pull request by kunaltyagi**
Change allows user to initiate the xterm widget with a script to run whenever the xterm plugin loads

### CODE REVIEW

**Comment by ablasdel** [comment]
I put some comments on how to move forward with making this work/merge-able with this in the issue here:

https://github.com/ros-visualization/rqt_common_plugins/issues/296

**Comment by kunaltyagi** [comment]
Squashed commits into one, ready to be tested

**Comment by ablasdel** [comment]
I get the following error when trying to test this. It looks like you didn't import argparse. Did you forget to check in some of the code? If you have it running on your computer this is definitely not the latest.

please update the PR and test it again. Thanks.

```
Traceback (most recent call last):
  File "./rqt_top", line 34, in <module>
    roslib.load_manifest(pkg)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslib/launcher.py", line 62, in load_manifest
    sys.path = _generate_python_path(package_name, _rospack) + sys.path
  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslib/launcher.py", line 93, in _generate_python_path
    m = rospack.get_manifest(pkg)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 159, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 198, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 190, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: rqt_top.top_plugin.Top
ROS path [0]=/opt/ros/hydro/share/ros
ROS path [1]=/home/ablasdel/groovy_caktin_ws/src
ROS path [2]=/opt/ros/hydro/share
ROS path [3]=/opt/ros/hydro/stacks
```

**Comment by ablasdel** [comment]
@kunaltyagi ping me when you get this going. Thanks!

**Comment by kunaltyagi** [comment]
@ablasdel  Editing on master now. See #403. Should we close this now?

**Pull request closed without merging**
