### PR TITLE
enable reconfigure resize for qt5

### PR DESCRIPTION
**Pull request by LeroyR**
does not crash on updated ubuntu 16.04

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Do you have a reference to a Qt ticket which shows when the bug was fixed?

Since Kinetic also supports Wily atm it might not be possible to update that before we drop building for that platform.

**Comment by LeroyR** [comment]
I could not find any reference that show that there was a bug.

Would be helpful if someone can verify if this crashes in Wily.

**Comment by dirk-thomas** [comment]
Yeah, that would be great to know.

**Comment by cottsay** [comment]
Also, have we verified that there is no longer a problem using both PySide and PyQt?

**Comment by dirk-thomas** [comment]
I am hesitant to merge the PR as-is. The segfault was a very real problem. And without any indication I am worried it will still happen (maybe only on some platforms) - especially since the master branch is being used across all ROS distros (Indigo to Kinetic atm.). So I think it either needs to be verified that the segfault is not happening anymore across all active ROS distros or a ticket referencing a fixed problem in Qt which enumerates the affected / fixed Qt versions needs to be identified.

**Comment by nxdefiant** [comment]
There should be at least a warning, could save some hours..

+1 for version check, there could be some people trying to use updated qt_common_plugins on old ubuntu images.

Patch confirmed working on Debian Testing, QT5 5.7 from 25th July 2016.

**Comment by dirk-thomas** [comment]
I just tried it on Xenial with Qt / PyQt 5.5.1 and it immediately segfaults when opening the plugin.

**Comment by dirk-thomas** [comment]
@charlieyan Maybe you can provide some more information here about your versions. Maybe that helps to figure out in which environment it does segfault and in which it doesn't.

**Comment by dirk-thomas** [comment]
I will close this ticket due to no response. Please feel free to comment and it can be reopened.

**Comment by nxdefiant** [comment]
Sorry, last time I checked this was not fixed, so why close it?

**Comment by dirk-thomas** [comment]
@nxdefiant The proposed patch doesn't work for me - it immediately segfaults (see [previous commment](https://github.com/ros-visualization/rqt_common_plugins/pull/417#issuecomment-276455583)). I also requested more information more than two months ago.

Therefore I closed the PR. If more information is provided so that we can iterate on this or the patch is being updated to not segfault this can be reopened.

**Comment by nxdefiant** [comment]
ok, to not loose this bug I added issue #450

**Pull request closed without merging**
