### PR TITLE
Add plugin to plot histogram

### PR DESCRIPTION
**Pull request by wkentaro**
Original Code: https://github.com/jsk-ros-pkg/jsk_visualization/tree/master/jsk_rqt_plugins
Suggestion: https://github.com/jsk-ros-pkg/jsk_recognition/pull/1837#issuecomment-278814833

Definition of histogram is an array of float values.

rqt_plot_hist_color_histogram
rqt_plot_hist_joint_effort

cc @k-okada

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The new plugin seems to be almost completely detached from `rqt_plot`. I think it would be better to maintain it in a separate repository.

If any changes / additions in `rqt_plot` would help with this plugin they can for sure be integrated here.

**Comment by k-okada** [comment]
add rqt_common_plugins/rqt_histogram ?

--
◉ Kei Okada


2017-03-09 3:42 GMT+09:00 Dirk Thomas <notifications@github.com>:

**Comment by dirk-thomas** [comment]
No, I meant a separate repository. This repository already contains way too many plugins. Making releases because of changes to a single package unnecessarily release all other packages. Using a separate repo will also allow you to make releases whenever you seem fit. Your nee plugin can still be added to the `rqt_common_plugins` metapackage if that is desired.

**Comment by k-okada** [comment]
humm, this node is already hosted at jsk-ros-pkg/jsk_visualization, so we can release anytime we want, but it is just a far from ROS mainland, so we think we'd better to put this node close to rqt_common_plugins, because it as more attention so more chance to have feedback, debugging, also less chance of loosing maintainers...

**Comment by dirk-thomas** [comment]
This repository will soon be split and most plugins will be moved into separate repositories for easier maintenance by multiple people and decoupling the releases of each plugin. Please see https://groups.google.com/d/msg/ros-sig-rqt/CMGkwUndJMI/5AVSksoXBgAJ for details.

Therefore I am closing this and encourage you to release the plugin from your repository. The plugin can certainly be listed as a dependency in the metapackage `rqt_common_plugins`. The only "requirement" for that is the promise that the plugin will be released quickly for upcoming ROS distros since `rqt_common_plugins` is part of the `simulators` and `viz` variants and therefore needs to be released before a beta is made available.

**Comment by k-okada** [comment]
Thank you for new info.

> The plugin can certainly be listed as a dependency in the metapackage
rqt_common_plugins.

I like this idea, but

> The only "requirement" for that is the promise that the plugin will be
released quickly for upcoming ROS distros

I think if we rely on this "promise", that's very dangerous, we have seen
many packages which is dropping as we moved to new ROS distros,

For example, on kinetic, we do not have smach any more, nor usb camera
drivers, maybe on Lunar we have more missing pacakages.
https://github.com/jbohren/executive_smach_visualization-release
https://discourse.ros.org/t/add-usb-cam-to-ros-kinetic-main-repository/607/5

Please also look at moveit decision, they once almost dropping from new ROS
distros.
https://discourse.ros.org/t/migration-to-one-github-repo-for-moveit/266

From above discourse topic, I found my concern is not popular, but if you
split current repository into multiple small packages, I  expect that we
can not keep even current set of rqt_common_plugins in upcoming release of
ROS distros, and I believe this will make everyone unhappy.

So my proposal is

- split metapackage and rest of current common package, if current
maintainer can not maintain that, let's find others. If no one, and you
understand that I have full time job and very limited time for doing this,
(now 2:30 am...)., I can do that.
- put (3radpary?) pckages into metapackage, that's good idea.
- If you decided to add 3rdparty packages into metapackge, please put that
package into ros-visualization, because package in personal repository is
very easy to get lost and very hard to take over. If that package is under
your(OSRF) control, you can easily add write permission to new maintainer.
- I know my idea is not popular, but please consider (again) putting
release package into OSRF repo and give access to anyone who help for
 release (apart from maintain package) so that you do not have ask for
release again and again, like
https://discourse.ros.org/t/lunar-release-progress/1558/6






--
◉ Kei Okada


2017-04-25 1:44 GMT+09:00 Dirk Thomas <notifications@github.com>:

**Comment by dirk-thomas** [comment]
@k-okada Splitting the repo or not doesn't change the fact that some plugins receive zero attention (just look at the list of open issues in this repo). But it allows us to remove plugins which are not maintained / are not working from the metapackage much easier. Also each plugin can have a dedicated maintainer and that person can release whatever and whenever he wants to (and doesn't have to coordinate with the other 20 plugins).

While we recommend maintainers to place their rqt plugins in this org unit as well as place the release repo into `ros-gbp` we can't force anyone to do that. Also the fact that we do have permission to repos hosted on `ros-*` org units does by no means imply that we (as in OSRF) will to the release into new distros for the maintainer.

After the split I will open tickets on the new repos asking for new maintainers for some of the plugins. We will see how much response we will get :crossed_fingers:

**Comment by k-okada** [comment]
> After the split I will open tickets on the new repos asking for new maintainers for some of the plugins. We will see how much response we will get :crossed_fingers:

@dirk-thomas that's good idea, i'm concerning not how much attention we get now, but how long these attention and effort continues. So let's evaluate a year later.

> allows us to remove plugins which are not maintained / are not working from the metapackage much easier

My theory is;
- There might be packages/plugins that is not maintained, but still very useful and if we drop these software, someone will re-implement that feature -> http://www.willowgarage.com/blog/2010/04/27/reinventing-wheel
- This because that people usually like to write their own code rather than keep maintaining other's code. Or keep maintains existing code is difficult.
- Since ROS is now stable stage rather than development stage, so we have to find a new way to keep maintained
- We should put higher priority on (1) releasing new distro, (2) merge really really bad bugs, issues, (3) fix problem, answer question, (4) add new features.
- Since the code is stable stage and it becomes very hard to find new maintainers (because more poeple like to write new code, from my theory), who can continue working for a long period, we try to  find new way.
- My expectation is we should concentrate (1) (2) and for (3) and (4) regards as bonus.

See if I'm correct or not...

**Pull request closed without merging**
