### PR TITLE
Show file size of bag file at the end of rqt_bag

### PR DESCRIPTION
**Pull request by garaemon**
rqt_bag__bag - rqt_001

### CODE REVIEW

**Comment by garaemon** [comment]
The file size is updated when rqt_bag is used to record topics.

**Comment by trainman419** [comment]
How does this work when opening multiple bag files at the same time?

**Comment by garaemon** [comment]
It will be total file size.
https://github.com/ros-visualization/rqt_common_plugins/pull/347/files#diff-3b3c261b71211cf3fd0c6b379c0eddf8R177

**Comment by garaemon** [comment]
selection_002

**Comment by dirk-thomas** [comment]
Thank you for the contribution and sorry for the late response. I have cherry-picked you patch with some minor code style changes in dec5fa6d7c9d046f11d4b4e309680e8ae60e60b9.

**Pull request closed without merging**
