### PR TITLE
rqt_plot: Plot bool fields

### PR DESCRIPTION
**Pull request by DLu**
Add the capability to plot bool fields in composite messages.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Can you please provide a reproducible example.

**Comment by DLu** [comment]
```
#!/usr/bin/python

import rospy
from sensor_msgs.msg import BatteryState
import random

rospy.init_node('x')
pub = rospy.Publisher('/battery', BatteryState, queue_size=1)
r = rospy.Rate(2)
while not rospy.is_shutdown():
  b = BatteryState()
  b.header.stamp = rospy.Time.now()
  b.present = random.random() > 0.5
  b.voltage = random.random()
  pub.publish(b)
  r.sleep()

```

Run the above script, and then run this: 
`! ~/ > rqt_plot /battery/voltage /battery/present`

Before the pull request, only voltage will be published. After, both signals we be published.

**Comment by dirk-thomas** [comment]
Thank you. This works well for me.

Maybe the message should be adjusted to mention that it is a `boolean` field rather then a `numeric` one. I would suggest adding `topic_kind = 'boolean' if field_class == bool else 'numeric'` and then use that as a placeholder for both messages.

**Comment by DLu** [comment]
Good thought. Updated.

**Comment by dirk-thomas** [comment]
Thanks.

**Pull request merged**
