### PR TITLE
additionally support Qt5

### PR DESCRIPTION
**Pull request by dirk-thomas**
With these patches the same code base can satisfy both of the following use cases (with only minimal `try / except` logic:

* continue to work with Qt 4 (in Indigo and Jade) relying on the forward compatibility provided by:

  * ros-visualization/python_qt_binding#31

* support Qt 5 (in Kinetic) using these changes:

  * ros-visualization/python_qt_binding#30
  * ros-visualization/qt_gui_core#64
  * ros-visualization/rqt#106

The version dependency on `python_qt_binding` ensures that the packages which use `QtWidgets` are getting the changes from ros-visualization/python_qt_binding#31.

This is required for a release into Kinetic.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
As a follow up of this PR the package `rqt_plot` will be moved into a separate repository since it requires a Qt version specific dependency on Qwt. Since I don't want to branch this repo for Kinetic `rqt_plot` is extracted since it requires branching.

**Comment by trainman419** [comment]
rqt_bag depends on rqt_plot, so that may need to move as well.

**Comment by dirk-thomas** [comment]
`rqt_bag` doesn't need to move. Only `rqt_plot` needs a different dependency in its manifest. `rqt_bag` can continue to use it even if it is in a different repo.

**Comment by trainman419** [comment]
The dependency chain now is `rqt_bag_plugins` -> `rqt_plot` -> `rqt_py_common`. Moving the middle item in that dependency chain out of the repository seems like it will cause confusion for people building from source, and I'm not convinced that tools like bloom or devel jobs are designed for that situation.

**Comment by dirk-thomas** [comment]
That is true. A circular dependency on the repository level is not fun and should be avoided. I might create a "relay" package then which just chooses the Qwt version. Then that package can be branches and `rqt_plot` and friends can stay in this repo (without a need to branch).

**Comment by dirk-thomas** [comment]
I created a "dependency only" package called `qwt_dependency` which lives outside of this repo and is now being used as a dependency: 3ac086c9fc844202fd35700345a03517f6ae9aa8

That way we can use Qwt 5 for Jade and older and Qwt 6.1 for Kinetic (once it becomes available as a system package or someone creates a custom package which we import into our apt repo).

**Comment by dirk-thomas** [comment]
With `PySide 2` there are no working backends for plotting at the moment. There are either no packages available upstream or the package is too old (in the case of matplotlib it supports PySide 2 only as of the upcoming release 2.1).

**Comment by dirk-thomas** [comment]
I posted on the SIG and am looking forward for feedback on these changes: https://groups.google.com/forum/#!topic/ros-sig-rqt/1zcA4xlQ3E0

**Pull request merged**
