### PR TITLE
New plugin rqt_plotxy

### LINKED ISSUE #69: trajectory plotter
Discussed [here](http://answers.ros.org/question/58907/has-anyone-written-a-trajectory-plotting-tool/)

### PR DESCRIPTION
**Pull request by rafael1193**
rqt_plot can plot topics with respect to time but sometimes it is useful to see its evolution in relation to another topic. For instance when representing trajectories, or doing other 2D scatter plots.

**rqt_plotxy** replaces time in the horizontal axis by another topic, so topics can be entered in (X, Y) pairs.

rqt_plotxy

May close #69

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The patch contains a lot of copied code. While copy-n-paste is easy in the first place it is expensive to maintain. Please consider either reusing code from the existing plugin or even extending the existing plugin to support both use cases.

Also you should customize the description of the package / main - currently they are indistinguishable from rqt_plot. Also the changelog is a one-to-one copy which does not apply to this new plugin. And the toplevel CMake file should not be checked in. That is custom to your workspace.

**Comment by rafael1193** [comment]
I removed all the repeated code and now it is using or inheriting `rqt_plot` classes. Plugin description was updated, changelog was corrected and the CMake file was removed.

I had to modify the `update_values` function `rqt_plot/data_plot/__init__.py` to include a named parameter that disables value sorting. This change doesn't affect `rqt_plot`, but it is necessary to `rqt_plotxy`.

**Comment by cbandera** [comment]
Hi @rafael1193,

I was working on a similar plugin for the last days, before I found your pull request. But it turned out, that we have a different understanding of a XY plot. I was looking for a possibility to plot array data,(i.e. anything defined as [ ] ) against any other array data. Your approach on the other hand focuses on plotting any scalar value against another scalar value tracked over time.

You can have a look at my implementation [on the rqt_plot_xy-branch of my fork](https://github.com/cbandera/rqt_common_plugins/tree/rqt_plot_xy).

I wonder if we could combine the two approaches somehow. I'd be happy to hear your feedback,

cbandera

**Comment by dirk-thomas** [comment]
I have applied your changes to the `rqt_plot` plugin (adding the keyword argument to make the sort optional) in 417fd3faf61f28f67295bd2f6c03d85b68c893fd.

Since this repo already contains way to many plugins I don't think more should be added since maintaining this big set becomes more and more a problem. Therefore I suggest you release your new plugin from a separate repo. With the change in `rqt_plot` you should be easily able to do so. Thanks.

Therefore I will close this PR.

**Pull request closed without merging**
