### PR TITLE
rqt_yn_btn (new plugin): rqt to ask user for yes/no input with service

### PR DESCRIPTION
**Pull request by wkentaro**
For https://github.com/jsk-ros-pkg/jsk_visualization/pull/521

image

```
rosrun rqt_yn_btn rqt_yn_btn
rosservice call /rqt_yn_btn
# push button here
# 'yes: true' or 'yes: false'
```

### CODE REVIEW

**Comment by wkentaro** [comment]
ping

**Comment by ablasdel** [comment]
I looked this over last week and I thought I made a comment but perhaps I forgot to hit the comment button.

My thoughts on this plugin is that is isn't universally useful enough to include in the main repos. But i definitely think you should add your plugin to the "Other Plugins" list here: http://wiki.ros.org/rqt/Plugins

@dirk-thomas @DorianScholz Do you have thoughts on this?

**Comment by dirk-thomas** [comment]
I do agree with @ablasdel. Conceptionally this plugin can't be used to "answer" multiple service calls at the same time, doesn't provide any feedback to the user what question he is supposed to answer etc. Therefore I don't think this should be merged.

Also the plugin doesn't have to be part of rqt_common_plugins. It can be perfectly managed and released from a separate repo. The goal will be anyway to not let the number of packages maintained in a single repo grow too much. Once an external plugin has been proved to be generally useful it can still be listed in the metapackage rqt_common_plugins in order to be a "default" plugin.

**Comment by ablasdel** [comment]
I will close this. @wkentaro Please release this package from your own github and add it to the plugins list I mentioned before.
Thanks

http://wiki.ros.org/rqt/Plugins
http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease

**Comment by wkentaro** [comment]
Thanks for your comments.
Actually the professor in my lab is discouraged to release a new package, because it takes his time..
When he got time to do that, we release the plugin as a separated package.

**Pull request closed without merging**
