### PR TITLE
rqt_reconfigure: add refresh button to re-scan reconfigure server list

### LINKED ISSUE #154: rqt_reconfigure) picks up parameters only upon its booting
A work-around [is documented](http://www.ros.org/wiki/rqt_reconfigure#Limitation).

### PR DESCRIPTION
**Pull request by k-okada**
please review carefelly, I'm not familier with both python nor qt, so I do not know what .ui file is, just to write code by guess, this fixes #154

### CODE REVIEW

**Comment by aleeper** [comment]
This seems to be a reasonable approach. (Did not test.)

**Comment by ablasdel** [comment]
This looks like it should work but I haven't tested. My main worry is that the function being called seems to have been dead code until this change. May have never been tested.

I might have some time to test next week.

**Comment by cottsay** [comment]
I just tested this, and the only issue is that when you click it, it closes all open widgets. I'd like to find a cleaner way to update it. I'll take a look this week.

**Comment by ablasdel** [comment]
@cottsay is this merge-able for the jade release or does that "close all widgets" thing need to get fixed?

**Comment by cottsay** [comment]
I just implemented a fix for the issue you mentioned. See https://github.com/ros-visualization/rqt_common_plugins/pull/319

Sorry it took so long.

**Comment by ablasdel** [comment]
Closing this in favor of #319

**Pull request closed without merging**
