### PR TITLE
Added image orinatation, keep aspec ratio or stretch image

### PR DESCRIPTION
**Pull request by oxoocoffee**
Added Stretch button next to reload
Added rotate image
Added some tooltips

### CODE REVIEW

**Comment by ablasdel** [comment]
@dirk-thomas Can you take a look at this one?

**Comment by dirk-thomas** [comment]
@oxoocoffee Please avoid any kind of whitespace changes in your patch and any new / changed code should follow the style of the file.

**Comment by oxoocoffee** [comment]
I will in future :) I have more stuff coming :) But will change only what needs to be changed.

**Comment by dirk-thomas** [comment]
Please also update this PR since the diff is hardly readable in the current version.

**Comment by oxoocoffee** [comment]
Sorry for long delay. It will be done this weekend

**Pull request closed without merging**
