### PR TITLE
rqt_image_view: use smooth transformation for image scaling

### PR DESCRIPTION
**Pull request by samuelba**
Is there a reason for not using the `Qt::SmoothTransformation` when scaling the image inside the `ratio_layouted_frame`? If not I would propose this change. Especially low resolution images e.g. from thermal cameras look much better when scaled.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
First of all the extra scaling step will require a full image copy including allocation. And second in a lot of use cases I am aware of the user wants to see the "exact" data from the sensor. "Smoothing" it will make it look "better" but also less accurate.

Maybe this could be a checkbox in the UI for the user to check?

**Comment by samuelba** [comment]
You are right, I will extend this with a checkbox in a few weeks.

**Comment by dirk-thomas** [comment]
Any news on updating this?

**Comment by samuelba** [comment]
Had no time yet, but it's on my list.

**Comment by samuelba** [comment]
I added now a checkbox to activate the smooth image scaling optionally.

**Comment by dirk-thomas** [comment]
Looks good to me. Thank you for iterating on it and sorry for the late merge.

**Pull request merged**
